# Generated by Django 4.0.4 on 2022-04-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_question", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("time_create", models.DateTimeField()),
                ("time_changed", models.DateTimeField()),
                ("name", models.CharField(max_length=150)),
                ("group", models.CharField(max_length=50)),
                ("member_gz_2021_2022", models.CharField(blank=True, max_length=10)),
                ("sex", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("marital_status", models.CharField(max_length=20)),
                ("living", models.CharField(max_length=50)),
                ("children", models.CharField(max_length=20)),
                ("work_status", models.CharField(max_length=50)),
                ("working_in_fishing_or_shipping", models.CharField(max_length=30)),
                ("working_maritime", models.CharField(max_length=30)),
                ("working_fishing_industry", models.CharField(max_length=30)),
                (
                    "working_fishing_technology",
                    models.CharField(blank=True, max_length=30),
                ),
                ("working_aquaculture", models.CharField(blank=True, max_length=30)),
                ("working_economic", models.CharField(blank=True, max_length=30)),
                ("working_it", models.CharField(blank=True, max_length=30)),
                ("working_other", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Answers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csv_reader.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csv_reader.user",
                    ),
                ),
            ],
        ),
    ]
