# Generated by Django 4.0.4 on 2022-04-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_question", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="ID")),
                ("time_create", models.DateTimeField(verbose_name="Время создания")),
                ("time_changed", models.DateTimeField(verbose_name="Время изменения")),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Фамилия, Имя, Отчество"
                    ),
                ),
                ("group", models.CharField(max_length=50, verbose_name="Группа")),
                (
                    "member_gz_2021_2022",
                    models.CharField(
                        blank=True,
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=10,
                        null=True,
                        verbose_name="Участник GZ 2021-2022",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("01", "Мужской"), ("10", "Женский")],
                        max_length=50,
                        verbose_name="Пол",
                    ),
                ),
                ("age", models.CharField(max_length=30, verbose_name="Возраст")),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("01", "Замужем/женат"), ("10", "Холост")],
                        max_length=50,
                        verbose_name="Семейное положение",
                    ),
                ),
                (
                    "living",
                    models.CharField(
                        choices=[
                            ("01", "с родителями"),
                            ("10", "отдельно от родителей"),
                        ],
                        max_length=50,
                        verbose_name="Проживаю",
                    ),
                ),
                (
                    "children",
                    models.CharField(
                        choices=[("01", "есть дети"), ("10", "нет детей")],
                        max_length=40,
                        verbose_name="Дети",
                    ),
                ),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("001", "учусь"),
                            ("010", "работаю"),
                            ("011", "учусь и работаю"),
                            ("100", "не учусь и не работаю"),
                        ],
                        max_length=50,
                        verbose_name="Занятость",
                    ),
                ),
                (
                    "working_in_fishing_or_shipping",
                    models.CharField(
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=30,
                        null=True,
                        verbose_name="Связана ли Ваша основная деятельность с рыбной отраслью и (или) мореходной деятельностью",
                    ),
                ),
                (
                    "working_maritime",
                    models.CharField(
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=30,
                        null=True,
                        verbose_name="морские профессии (судовождение, эксплуатация судовых энергетических установок)",
                    ),
                ),
                (
                    "working_fishing_industry",
                    models.CharField(
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=30,
                        null=True,
                        verbose_name="промышленное рыболовство",
                    ),
                ),
                (
                    "working_fishing_technology",
                    models.CharField(
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=30,
                        null=True,
                        verbose_name="технология рыбы и рыбных продуктов, морская биотехнология",
                    ),
                ),
                (
                    "working_aquaculture",
                    models.CharField(
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=30,
                        null=True,
                        verbose_name="аквакультура и рыбоводство",
                    ),
                ),
                (
                    "working_economic",
                    models.CharField(
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=30,
                        null=True,
                        verbose_name="экономика и управления морехозяйственной/рыбохозяйственной деятельностью",
                    ),
                ),
                (
                    "working_it",
                    models.CharField(
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=30,
                        null=True,
                        verbose_name="информационные технологии в морехозяйственной/рыбохозяйственной деятельности",
                    ),
                ),
                (
                    "working_other",
                    models.CharField(
                        choices=[("01", "Да"), ("10", "Нет")],
                        max_length=30,
                        null=True,
                        verbose_name="другое",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "answer_bin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0001", "-1"),
                            ("0010", "0"),
                            ("0011", "1"),
                            ("0100", "2"),
                            ("0101", "3"),
                            ("0110", "4"),
                            ("0111", "5"),
                            ("1000", "6"),
                            ("1001", "7"),
                            ("001", "1 Очень похож на меня"),
                            ("010", "2 Похож на меня"),
                            ("011", "3 В некоторой степени похож на меня"),
                            ("100", "4 Немного похож на меня"),
                            ("101", "5 Не похож на меня"),
                            ("110", "6 Совсем не похож на меня"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csv_reader.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csv_reader.user",
                    ),
                ),
            ],
        ),
    ]
